config/routes.rb
Rails.application.routes.draw do
  root 'repositories#index'
  get '/repositories', to: 'repositories#index'
  get '/form-page', to: 'pages#form_page'
  get '/repositories/:id/edit', to: 'repositories#edit', as: 'edit_repository'
  put '/repositories/:id/update', to: 'repositories#update', as: 'update_repository'
  resources :repositories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def form_page
    render partial: 'shared/form'
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  require 'octokit'

  def index
    client = Octokit::Client.new(access_token)
    @repos = client.repos.sort_by { |repo| repo.created_at }.reverse
  end

  def show
    @repository_data = Octokit::Client.new(access_token).repo(params[:id].to_i)
  end

  def new
    @repository = Repository.new(repository_params)
    if @repository.save
      redirect_to @repository
    else
      render 'new'
    end
  end

  def create
    client = Octokit::Client.new(access_token)
    repo_name = params[:name]

    begin
      client.create_repository(repo_name, options = {})
      flash[:success] = "Repository '#{repo_name}' created."
    rescue Octokit::UnprocessableEntity => e
      flash[:error] = e.message
    end

    redirect_to root_path
  end

  # EDIT
  def edit
    # ACCESS THE CORRECT REPO WITH A NEW INSTANCE
    client = Octokit::Client.new(access_token)
    # RETRIEVE THE REPO INFORMATION BASED ON THE ID; ID MUST BE PASSED AS AN INTEGER
    # THE RETRIEVED REPO IS ASSIGNED TO '@REPOSITORY_DATA' INSTANCE; THIS POPULATES THE FORM WITH
    # THE CURRENT REPOSITORY INFO
    @repository_data = client.repository(params[:id].to_i)
  end

  # UPDATE
  def update
    # INITIALIZE A NEW INSTANCE
    client = Octokit::Client.new(access_token)

    # RETRIEVE REPO ID AND ASSIGN IT TO 'REPO_ID'
    # repo_id = params[:id].to_i
    repo_id = params[:id].to_i
    puts "repo_id: #{repo_id}"

    new_name = params[:repository][:name]

    puts "new_name: #{new_name}"

    client.update_repository(repo_id, name: new_name)

    # REDIRECT TO THE REPOSITORY SHOW PAGE WITH THE UPDATED NAME
    redirect_to repository_path(repo_id)
  end

  # DESTROY
  def destroy
    Octokit::Client.new(access_token).delete_repo(params[:id].to_i)
    redirect_to root_path
  end

  private

  def access_token
    { access_token: ENV['GITHUB_TOKEN'] }
  end

  def repository_params
    params.require(:repository).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OctokitApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/repositories/edit.html.erb
<h1>Update the repo name</h1>
<p>Current repo name: <%= @repository_data.name %></p>

<%= form_tag update_repository_path(@repository_data.id), method: :put do %>
  <%= label_tag :name %>
  <div class="form-input">
    <%= text_field_tag 'repository[name]', @repository_data.name, placeholder: 'Enter Repository Name' %>
  </div>
  <div class="btn-submit">
    <%= submit_tag 'Update Name' %>
  </div>
<% end %>

app/views/repositories/index.html.erb
<div class="section">
  <div class="header">
    <h1 class="text-3xl font-bold underline">
      GitHub Repositories
    </h1>
  </div>
  <div class="btn-class">
    <%= link_to 'Create new repo', form_page_path, class:'border' %>
  </div>

  <div class="content-repo">
    <% @repos.each do |repo| %>
      <p class="btn-repo-name">
        <%= link_to repo.name, repository_path(repo.id) %>
      <p>
        Created on: <%= repo.created_at.in_time_zone("Australia/Sydney").strftime("%A, %d %B %Y %Z") %>
      </p>
      <hr>
    <% end %>
  </div>
</div>

app/views/repositories/show.html.erb
<h1>
  Repo Name: <%= @repository_data.name %>
</h1>
<p> :: </p>
<h2>
  Description: <%= @repository_data.description %>
</h2>
<p> :: </p>
<h2>
  Last updated on: <%= @repository_data.created_at %>
</h2>
<p> :: </p>
<h2>
  Last updated on: <%= @repository_data.created_at %>
</h2>
<%= button_to 'Delete', repository_path, method: :delete %>
<%= link_to 'Edit', edit_repository_path(@repository_data.id) %>

app/views/shared/_form.html.erb
<%= form_with url: repositories_path, method: :post do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit "Create Repository" %>
<% end %>